namespace Managers.SoundManager.Enums
{
public enum SoundId
{
    Blackhole,
    SparksElectr_,
    HitIntoPlayer,
    PigeonSpaceSuitAttack,
    UFO,
    JumpDefault,
    JumpBooster,
    JumpBreakable,
    JumpCloud,
    Peasability,
    Cornability,
    Seedability,
    Victory,
    GoldenBean,
    JumperMusic,
    Loose,
    Spaceambient,
    ChompTamagoch,
    CuteTamagoch,
    Scratchham,
    LobbyLoop,
    FinalLoop,
    UI_ButtonClick,
    UI_ButtonBuy,
    UI_ButtonCancel,
}
}
